version: '3'

services:
  teste-postgres-compose:
    image: postgres:14.0
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /home/docker/postgres-14:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "15432:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge